name: server
description: Terafy server.
version: 0.2.1
publish_to: "none"
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.0

# Add regular dependencies here.
dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  postgres: ^3.0.0-1
  common:
    path: ../common
  hotreloader: ^3.0.4
  crypto: ^3.0.3
  dart_jsonwebtoken: ^2.10.0
  dotenv: ^4.1.0
  uuid: ^4.5.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
  mockito: ^5.4.4
  build_runner: ^2.4.8
  mocktail: ^1.0.1
